# Steps:
# 1a. Update package cache
# 1b. Install required packages
# 2. Disable virbr0
# 3a. List existing bridges
# 3b. Create netplan files for bridges
# 3c. Apply netplan configurations
# 4. Profit

- name: Step 1a - Update APT package cache
  apt:
    update_cache: true
    cache_valid_time: 0
  retries: 2
  delay: 5
  tags: [ kvm-install, always ]

- name: Step 1b - Install required packages
  apt:
    state: present
    pkg: "{{ kvm_required_packages + kvm_required_packages_user | default([])  }}"
  retries: 2
  delay: 5
  tags: [ kvm-install, always ]

- name: Step 2 - Remove virbr0
  command: virsh net-autostart --disable default
  become: yes
  tags: [ remove-virbr0, always ]

- debug:
    var: kvm_required_bridges
  tags: [ never, debug ]

- name: Step 3a - List existing bridges
  shell: brctl show | tail -n +2 | awk '{ print $1 }'
  register: existing_bridges
  become: true
  tags: [ create-bridges, always ]

- debug:
    msg: "{{ existing_bridges }}"
  tags: [ never, debug ]

# Always create netplan files so we can apply changes between runs
- name: Step 3b - Create netplan files for bridges, replace if different
  template:
    src: netplan_bridge.yaml.j2
    dest: /etc/netplan/{{item.name}}.yaml
    owner: root
    group: root
    mode: '0644'
    force: yes
  with_items: "{{ kvm_required_bridges }}"
  tags: [ create-bridges, always ]

- name: Step 3c - Apply all netplan configuration(s)
  command: netplan apply
  become: true
  tags: [ create-bridges, always ]

